const countryObject = {
  PYF: "French Polynesia",
  MAF: "Saint Martin",
  VEN: "Venezuela",
  REU: "Réunion",
  SLV: "El Salvador",
  DMA: "Dominica",
  GIB: "Gibraltar",
  KEN: "Kenya",
  BRA: "Brazil",
  MDV: "Maldives",
  USA: "United States",
  COK: "Cook Islands",
  NIU: "Niue",
  SYC: "Seychelles",
  CAF: "Central African Republic",
  TKL: "Tokelau",
  VUT: "Vanuatu",
  GMB: "Gambia",
  GUY: "Guyana",
  FLK: "Falkland Islands",
  BEL: "Belgium",
  ESH: "Western Sahara",
  TUR: "Turkey",
  VCT: "Saint Vincent and the Grenadines",
  PAK: "Pakistan",
  ALA: "Åland Islands",
  IRN: "Iran",
  IDN: "Indonesia",
  NZL: "New Zealand",
  AFG: "Afghanistan",
  GUM: "Guam",
  ALB: "Albania",
  COD: "DR Congo",
  CIV: "Ivory Coast",
  SDN: "Sudan",
  TLS: "Timor-Leste",
  LUX: "Luxembourg",
  SAU: "Saudi Arabia",
  KHM: "Cambodia",
  NPL: "Nepal",
  GUF: "French Guiana",
  MYS: "Malaysia",
  RWA: "Rwanda",
  THA: "Thailand",
  ATA: "Antarctica",
  JOR: "Jordan",
  CHE: "Switzerland",
  COM: "Comoros",
  UNK: "Kosovo",
  IMN: "Isle of Man",
  MNE: "Montenegro",
  HKG: "Hong Kong",
  JEY: "Jersey",
  TJK: "Tajikistan",
  BGR: "Bulgaria",
  EGY: "Egypt",
  MWI: "Malawi",
  CPV: "Cape Verde",
  BEN: "Benin",
  MAR: "Morocco",
  IRL: "Ireland",
  MDA: "Moldova",
  DNK: "Denmark",
  TKM: "Turkmenistan",
  FSM: "Micronesia",
  MCO: "Monaco",
  BRB: "Barbados",
  DZA: "Algeria",
  ATF: "French Southern and Antarctic Lands",
  ERI: "Eritrea",
  LSO: "Lesotho",
  TZA: "Tanzania",
  MLI: "Mali",
  NER: "Niger",
  AND: "Andorra",
  GBR: "United Kingdom",
  DEU: "Germany",
  VIR: "United States Virgin Islands",
  SOM: "Somalia",
  SXM: "Sint Maarten",
  CMR: "Cameroon",
  DOM: "Dominican Republic",
  GIN: "Guinea",
  NAM: "Namibia",
  MSR: "Montserrat",
  SGS: "South Georgia",
  SEN: "Senegal",
  BVT: "Bouvet Island",
  SLB: "Solomon Islands",
  FRA: "France",
  SHN: "Saint Helena, Ascension and Tristan da Cunha",
  MAC: "Macau",
  ARG: "Argentina",
  BIH: "Bosnia and Herzegovina",
  AIA: "Anguilla",
  GGY: "Guernsey",
  DJI: "Djibouti",
  KNA: "Saint Kitts and Nevis",
  SYR: "Syria",
  PRI: "Puerto Rico",
  PER: "Peru",
  SMR: "San Marino",
  AUS: "Australia",
  NCL: "New Caledonia",
  JAM: "Jamaica",
  KAZ: "Kazakhstan",
  SLE: "Sierra Leone",
  PLW: "Palau",
  KOR: "South Korea",
  SPM: "Saint Pierre and Miquelon",
  BLZ: "Belize",
  PNG: "Papua New Guinea",
  ISL: "Iceland",
  ASM: "American Samoa",
  BFA: "Burkina Faso",
  PRT: "Portugal",
  TWN: "Taiwan",
  JPN: "Japan",
  CHN: "China",
  LBN: "Lebanon",
  LKA: "Sri Lanka",
  GTM: "Guatemala",
  SRB: "Serbia",
  MDG: "Madagascar",
  SWZ: "Eswatini",
  ROU: "Romania",
  ATG: "Antigua and Barbuda",
  CUW: "Curaçao",
  ZMB: "Zambia",
  ZWE: "Zimbabwe",
  TUN: "Tunisia",
  ARE: "United Arab Emirates",
  MNG: "Mongolia",
  NOR: "Norway",
  GRL: "Greenland",
  URY: "Uruguay",
  BHS: "Bahamas",
  RUS: "Russia",
  VGB: "British Virgin Islands",
  WLF: "Wallis and Futuna",
  TCD: "Chad",
  LCA: "Saint Lucia",
  YEM: "Yemen",
  UMI: "United States Minor Outlying Islands",
  SWE: "Sweden",
  SJM: "Svalbard and Jan Mayen",
  LAO: "Laos",
  LVA: "Latvia",
  COL: "Colombia",
  GRD: "Grenada",
  BLM: "Saint Barthélemy",
  CAN: "Canada",
  HMD: "Heard Island and McDonald Islands",
  IND: "India",
  GNB: "Guinea-Bissau",
  MKD: "North Macedonia",
  PRY: "Paraguay",
  HRV: "Croatia",
  CRI: "Costa Rica",
  UGA: "Uganda",
  BES: "Caribbean Netherlands",
  BOL: "Bolivia",
  TGO: "Togo",
  MYT: "Mayotte",
  MHL: "Marshall Islands",
  PRK: "North Korea",
  NLD: "Netherlands",
  IOT: "British Indian Ocean Territory",
  MLT: "Malta",
  MUS: "Mauritius",
  NFK: "Norfolk Island",
  HND: "Honduras",
  ESP: "Spain",
  EST: "Estonia",
  KGZ: "Kyrgyzstan",
  CHL: "Chile",
  BMU: "Bermuda",
  GNQ: "Equatorial Guinea",
  LBR: "Liberia",
  PCN: "Pitcairn Islands",
  LBY: "Libya",
  LIE: "Liechtenstein",
  VAT: "Vatican City",
  CXR: "Christmas Island",
  OMN: "Oman",
  PHL: "Philippines",
  POL: "Poland",
  FRO: "Faroe Islands",
  BHR: "Bahrain",
  BLR: "Belarus",
  SVN: "Slovenia",
  GLP: "Guadeloupe",
  QAT: "Qatar",
  VNM: "Vietnam",
  MRT: "Mauritania",
  SGP: "Singapore",
  GEO: "Georgia",
  BDI: "Burundi",
  NRU: "Nauru",
  SSD: "South Sudan",
  WSM: "Samoa",
  CCK: "Cocos (Keeling) Islands",
  COG: "Republic of the Congo",
  CYP: "Cyprus",
  KWT: "Kuwait",
  TTO: "Trinidad and Tobago",
  TUV: "Tuvalu",
  AGO: "Angola",
  TON: "Tonga",
  GRC: "Greece",
  MOZ: "Mozambique",
  MMR: "Myanmar",
  AUT: "Austria",
  ETH: "Ethiopia",
  MTQ: "Martinique",
  AZE: "Azerbaijan",
  UZB: "Uzbekistan",
  BGD: "Bangladesh",
  ARM: "Armenia",
  NGA: "Nigeria",
  ZAF: "South Africa",
  BRN: "Brunei",
  ITA: "Italy",
  FIN: "Finland",
  ISR: "Israel",
  ABW: "Aruba",
  NIC: "Nicaragua",
  HTI: "Haiti",
  KIR: "Kiribati",
  TCA: "Turks and Caicos Islands",
  CYM: "Cayman Islands",
  UKR: "Ukraine",
  MEX: "Mexico",
  PSE: "Palestine",
  FJI: "Fiji",
  SVK: "Slovakia",
  GHA: "Ghana",
  SUR: "Suriname",
  CUB: "Cuba",
  BTN: "Bhutan",
  HUN: "Hungary",
  STP: "São Tomé and Príncipe",
  IRQ: "Iraq",
  CZE: "Czechia",
  LTU: "Lithuania",
  MNP: "Northern Mariana Islands",
  BWA: "Botswana",
  PAN: "Panama",
  GAB: "Gabon",
  ECU: "Ecuador",
};

export default countryObject;
