const responseObject = () => {
  const responseObject = {
    general: {
      title: "general information",
      type: "general",
      nameOfficial: "",
      nameCommon: "",
      nameNative: [],
      coatOfArmsSvgUrl: null,
      coatOfArmsPngUrl: null,
      coatOfArmsJpgUrl: null,
      coatOfArmsAlt: "",
      currencies: null,
      altSpellings: [],
      flagPng: "",
      flagSvg: "",
      flagAlt: "",
    },
    geography: {
      title: "geography",
      type: "geography",
      continents: [],
      region: "",
      subregion: "",
      latlng: [],
      borders: [],
      capital: "",
      capitalLatlng: [],
      area: null,
      timezones: [],
      landlocked: null,
      googleMaps: "",
      openStreetMaps: "",
    },

    communicationsAndCodes: {
      title: "communications & codes",
      type: "communicationsAndCodes",
      tld: [],
      idd: null,
      postalCode: { format: "", regex: "" },

      cca2: "",
      ccn3: "",
      cca3: "",
      cioc: "",
      flag: "",
      fifa: "",
    },
    intlRelations: {
      title: "international relations",
      type: "intlRelations",
      independent: null,
      status: "",
      unMember: null,
    },
    demographics: {
      title: "demographics",
      type: "demographics",
      demonyms: [],
      population: null,
      gini: [],
      languages: [],
    },
    additional: {
      title: "additional info",
      type: "additional",
      translations: [],
      startOfWeek: "",
      carSigns: [],
      carSide: "",
    },
  };
  return responseObject;
};
export default responseObject;
