const languageObject = {
  fra: "French",
  spa: "Spanish",
  eng: "English",
  swa: "Swahili",
  por: "Portuguese",
  div: "Maldivian",
  rar: "Cook Islands Māori",
  niu: "Niuean",
  crs: "Seychellois Creole",
  sag: "Sango",
  smo: "Samoan",
  tkl: "Tokelauan",
  bis: "Bislama",
  deu: "German",
  nld: "Dutch",
  ber: "Berber",
  mey: "Hassaniya",
  tur: "Turkish",
  urd: "Urdu",
  swe: "Swedish",
  fas: "Persian (Farsi)",
  ind: "Indonesian",
  mri: "Māori",
  nzs: "New Zealand Sign Language",
  prs: "Dari",
  pus: "Pashto",
  tuk: "Turkmen",
  cha: "Chamorro",
  sqi: "Albanian",
  kon: "Kikongo",
  lin: "Lingala",
  lua: "Tshiluba",
  ara: "Arabic",
  tet: "Tetum",
  ltz: "Luxembourgish",
  khm: "Khmer",
  nep: "Nepali",
  msa: "Malay",
  kin: "Kinyarwanda",
  tha: "Thai",
  gsw: "Swiss German",
  ita: "Italian",
  roh: "Romansh",
  zdj: "Comorian",
  srp: "Serbian",
  glv: "Manx",
  cnr: "Montenegrin",
  zho: "Chinese",
  nrf: "Jèrriais",
  rus: "Russian",
  tgk: "Tajik",
  bul: "Bulgarian",
  nya: "Chewa",
  gle: "Irish",
  ron: "Romanian",
  dan: "Danish",
  tir: "Tigrinya",
  sot: "Sotho",
  cat: "Catalan",
  som: "Somali",
  afr: "Afrikaans",
  her: "Herero",
  hgm: "Khoekhoe",
  kwn: "Kwangali",
  loz: "Lozi",
  ndo: "Ndonga",
  tsn: "Tswana",
  nor: "Norwegian",
  grn: "Guaraní",
  bos: "Bosnian",
  hrv: "Croatian",
  nfr: "Guernésiais",
  aym: "Aymara",
  que: "Quechua",
  jam: "Jamaican Patois",
  kaz: "Kazakh",
  pau: "Palauan",
  kor: "Korean",
  bjz: "Belizean Creole",
  hmo: "Hiri Motu",
  tpi: "Tok Pisin",
  isl: "Icelandic",
  jpn: "Japanese",
  sin: "Sinhala",
  tam: "Tamil",
  mlg: "Malagasy",
  ssw: "Swazi",
  pap: "Papiamento",
  bwg: "Chibarwe",
  kck: "Kalanga",
  khi: "Khoisan",
  ndc: "Ndau",
  nde: "Northern Ndebele",
  sna: "Shona",
  toi: "Tonga",
  tso: "Tsonga",
  ven: "Venda",
  xho: "Xhosa",
  zib: "Zimbabwean Sign Language",
  mon: "Mongolian",
  nno: "Norwegian Nynorsk",
  nob: "Norwegian Bokmål",
  smi: "Sami",
  kal: "Greenlandic",
  lao: "Lao",
  lav: "Latvian",
  hin: "Hindi",
  pov: "Upper Guinea Creole",
  mkd: "Macedonian",
  mah: "Marshallese",
  mlt: "Maltese",
  mfe: "Mauritian Creole",
  pih: "Norfuk",
  est: "Estonian",
  kir: "Kyrgyz",
  lat: "Latin",
  fil: "Filipino",
  pol: "Polish",
  fao: "Faroese",
  bel: "Belarusian",
  slv: "Slovene",
  vie: "Vietnamese",
  kat: "Georgian",
  run: "Kirundi",
  nau: "Nauru",
  ell: "Greek",
  tvl: "Tuvaluan",
  ton: "Tongan",
  mya: "Burmese",
  de: "German",
  amh: "Amharic",
  aze: "Azerbaijani",
  uzb: "Uzbek",
  ben: "Bengali",
  hye: "Armenian",
  nbl: "Southern Ndebele",
  nso: "Northern Sotho",
  zul: "Zulu",
  fin: "Finnish",
  heb: "Hebrew",
  hat: "Haitian Creole",
  gil: "Gilbertese",
  ukr: "Ukrainian",
  fij: "Fijian",
  hif: "Fiji Hindi",
  slk: "Slovak",
  dzo: "Dzongkha",
  hun: "Hungarian",
  arc: "Aramaic",
  ckb: "Sorani",
  ces: "Czech",
  lit: "Lithuanian",
  cal: "Carolinian",
};
export default languageObject;
